// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVF2WBmEYremQBsMMHH93z9BAMEPXVXg',
    appId: '1:621780794063:web:f2c3ddebb8e3eea845d5ba',
    messagingSenderId: '621780794063',
    projectId: 'gearbox-dad7c',
    authDomain: 'gearbox-dad7c.firebaseapp.com',
    storageBucket: 'gearbox-dad7c.firebasestorage.app',
    measurementId: 'G-KWX227GSNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzxeVVUzJ69UDYFq05de0Bh-M59ckVUE',
    appId: '1:621780794063:android:9f8aef44f2c0f97045d5ba',
    messagingSenderId: '621780794063',
    projectId: 'gearbox-dad7c',
    storageBucket: 'gearbox-dad7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Aoxeu5PRNa7iug9ASAqUbfFyZqU9C8M',
    appId: '1:621780794063:ios:a270819a4da67c8f45d5ba',
    messagingSenderId: '621780794063',
    projectId: 'gearbox-dad7c',
    storageBucket: 'gearbox-dad7c.firebasestorage.app',
    iosBundleId: 'com.example.garageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Aoxeu5PRNa7iug9ASAqUbfFyZqU9C8M',
    appId: '1:621780794063:ios:a270819a4da67c8f45d5ba',
    messagingSenderId: '621780794063',
    projectId: 'gearbox-dad7c',
    storageBucket: 'gearbox-dad7c.firebasestorage.app',
    iosBundleId: 'com.example.garageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyVF2WBmEYremQBsMMHH93z9BAMEPXVXg',
    appId: '1:621780794063:web:5a19d9769d2817d045d5ba',
    messagingSenderId: '621780794063',
    projectId: 'gearbox-dad7c',
    authDomain: 'gearbox-dad7c.firebaseapp.com',
    storageBucket: 'gearbox-dad7c.firebasestorage.app',
    measurementId: 'G-7HHNEP7KN0',
  );
}
